### PR TITLE
fix: building to executable

### PR DESCRIPTION
**Pull request by Julusian**
fixes: #23 

I have tried to keep this as minimal and lightweight as possible.

The json package has no dependencies, so should have minimal impact to dependency tree size. I did try with plain npm commands, but doing an uninstall installs everything else which felt too wasteful.

I have tested this on both windows and linux and it now builds a binary on both and I can still use the pouchdb endpoint

### CODE REVIEW

**Comment by ronag** [comment]
LGTM. Have you reported the issue upstream? Please add a link to the relevant issue so we can follow it.

**Comment by Julusian** [comment]
Yes, there is already a rather old issue against pkg for this https://github.com/zeit/pkg/issues/75 and I opened one against express-pouchdb yesterday https://github.com/pouchdb/pouchdb-server/issues/326

**Comment by ronag** [comment]
Can you add the links to the README and then I'm happy to merge. Thanks!

**Comment by Julusian** [comment]
links added

**Pull request merged**
