### PR TITLE
Expose couchdb for clients to get changes stream

### LINKED ISSUE #15: Websocket data endpoint
There is no way for a client to be notified of new media without polling the scanner at regular intervals.

By having a websocket endpoint in the scanner, clients who want real-time media updates could connect directly (not via AMCP) and get them streamed.

### PR DESCRIPTION
**Pull request by Julusian**
Closes #15

### CODE REVIEW

**Comment by ronag** [comment]
I don't think it's a good idea to have 2 pouchdb instances to the same db. You need to either use the pouch-express pouch instance for the rest or use the `db` instance in pouch-express.

**Comment by Julusian** [comment]
I did try passing db to express-pouchdb but it just errored.
All the express-pouchdb docs show them passing in the main PouchDB type mostly before creating db

**Comment by ronag** [comment]
The outer dB instance could ref localhost. That would resolve it.

**Comment by Julusian** [comment]
Doing that would pollute the log as all the db ops for the scanner would now be present there. Is this a problem to you?
It also doesn't feel right having express connect to itself so that some route can have database access

**Comment by Julusian** [comment]
I was referring to the extra logging there

**Comment by ronag** [comment]
Extra loggingis fine for me

**Comment by Julusian** [comment]
I've made that change now

**Pull request merged**
